chore(deps): add dependabot bundler
weaveworks-liquidmetal/flintlock pull request #647
Opened 2023-03-03 07:59 UTC by Skarlso

The bundler PRs are getting out of control. Let's try and rein them in.

kind/feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits into logical changes
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

2023-03-03 11:06 UTC, Skarlso commented
The resulting PR looks good https://github.com/weaveworks-liquidmetal/flintlock/pull/649

2023-03-03 12:02 UTC, yitsushi approved these changes

2023-03-03 12:04 UTC, yitsushi requested changes
just checked a generated PR. That doesn't work
![image](https://user-images.githubusercontent.com/183191/222715937-2897c169-83f7-4fc3-8301-eb0636b904d5.png)

2023-03-03 12:05 UTC, Skarlso commented
Ah freck.

2023-03-03 12:07 UTC, Skarlso commented
I guess I need a way to pass in a signing key to the bot.

2023-03-04 13:15 UTC, Skarlso commented
Finalllly! The latest version added verification. I'll release it and use that. Hopefully, it will work. :D

<img width="643" alt="Screenshot 2023-03-04 at 14 14 38" src="https://user-images.githubusercontent.com/182850/222903901-4330f2a2-82c8-4227-9185-460f6160857f.png">

2023-03-04 15:32 UTC, Skarlso commented
<img width="938" alt="Screenshot 2023-03-04 at 16 32 19" src="https://user-images.githubusercontent.com/182850/222914823-3eda1fd9-3cfe-43bb-9e60-fde045b98f29.png">

2023-03-04 20:09 UTC, Skarlso commented on CONTRIBUTING.md
> +There is an action that will periodically bundle dependabot pull requests into a single
I can extend this if more info is required. Maybe with a link to the action once it's available. Or a sample PR once there is one. :)

2023-03-04 20:57 UTC, yitsushi approved these changes

2023-03-04 20:57 UTC, merged